@startuml
title 基于GitHub的实验管理平台--类图
class users {
    <b>user_id</b> （用户ID）
    name （用户真实姓名）
    github_username （用户GitHub账号）
    update_date （用户GitHub账号修改日期）
    password （用户密码）
    disable （用户是否禁用）
}
class teachers{
    <b>teacher_id</b> （老师工号）
    department （老师所属部门）
}
class students{
    <b>student_id</b> （学生学号）
    major	（专业）
    class （班级）
    enrollment_year	（入学年份）
    web_sum （个人GitHub网址是否正确）
}
users <|- students
users <|-- teachers

class courses {
    <b>course_id</b> （课程号）
    course_name （课程名称）
    course_term	 （开课学期）
    course_major （开课专业）
    course_teacher （任课老师）
    course_num （课程人数）
    course_class （开课班级）


}

class experiments {
    <b>course_id</b> （课程号）
    <b>experiment_id</b> （实验编号）
    experiment_title	（实验题目）
    experiment_content	（实验内容）
    experiment_date （实验截至时间）
}

class courses_scores {
	<b>course_id</b> （课程编号）
    <b>student_id</b> （学生学号）
    course_score （课程成绩）
    course_comment （课程评语）
    course_date （批改日期）

}

class experiments_scores {
    <b>course_id</b> （课程编号）
    <b>experiment_id</b> （实验编号）
    <b>student_id</b> （学号）
    experiment_score （实验成绩）
    experiment_comment （实验评语）
    experiment_date （批改日期）


}

class ScoreItem {
	<b>course_id</b> （课程编号）
    <b>experiment_id</b> （实验编号）
    <b>ScoreItem_id</b> （实验评分点编号）
    ScoreItem_name	（实验评分点名称）
    ScoreItem_content	（实验评分点内容）
}
class ScoreItem_Scores {
    <b>course_id</b> （课程编号）
    <b>experiment_id</b> （实验编号）
    <b>ScoreItem_id</b> （评分点编号）
    <b>student_id</b> （学号）
   ScoreItem_score （实验评分点成绩）
   ScoreItem_comment （实验评分点评语）
   ScoreItem_date （批改日期）

}
students "1" -- "n"  courses
courses_scores "1" -- "n"  experiments_scores
teachers "1" -- "n"  courses
courses "1" -- "n" experiments
courses "1" -- "1" courses_scores
experiments "1" -- "1" experiments_scores
experiments "1" - "n" ScoreItem
experiments_scores "1" -- "n"  ScoreItem_Scores
ScoreItem "1" -- "1" ScoreItem_Scores


@enduml
