@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #Black
skinparam titleFontSize 24
Title 显示课程作业顺序图

actor 用户
participant  API服务
participant  用户主页面
database 数据库存储
用户-> 用户主页面:选择课程
用户主页面->API服务:发送请求 并传入course_id
API服务->数据库存储:服务请求对应course_id的课程信息
数据库存储->API服务:返回对应的课程信息
API服务->用户主页面:显示课程信息
@enduml
