@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #Black
skinparam titleFontSize 24
Title 评定成绩顺序图

actor 老师
participant  API服务
participant  老师主页面
database 数据库存储
老师-> 老师主页面:进入对应课程的学生列表页并点击评定成绩，
老师主页面->老师主页面:输入实验和评分点的成绩及评语
老师主页面->API服务:发送成绩及评语
API服务->数据库存储:请求存储请求数据
数据库存储->数据库存储:更新或添加数据库该学生的成绩
数据库存储->API服务:返回对应课程的成绩
API服务->老师主页面:显示评定的成绩
@enduml
